import type { SnapshotDiff } from '@/lib/zuper/diff';

export function buildGoLiveEmail({
  orgName,
  saEmail,
  generatedAt,
  diff,
  pdfUrl,
}: {
  orgName: string;
  saEmail: string;
  generatedAt: string;
  diff: SnapshotDiff;
  pdfUrl: string | null;
}) {
  const date = new Date(generatedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  function diffRows(label: string, d: { added: { name: string }[]; removed: { name: string }[]; renamed: { name: string; oldName?: string }[] }) {
    if (!d.added.length && !d.removed.length && !d.renamed.length) return '';
    return `
      <p style="margin:12px 0 6px;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:2px;color:#9CA3AF;">${label}</p>
      ${d.added.map((x) => `<p style="margin:3px 0;font-size:13px;color:#16A34A;">+ Added: ${x.name}</p>`).join('')}
      ${d.removed.map((x) => `<p style="margin:3px 0;font-size:13px;color:#DC2626;">- Removed: ${x.name}</p>`).join('')}
      ${d.renamed.map((x) => `<p style="margin:3px 0;font-size:13px;color:#F97316;">~ Renamed: ${x.oldName} → ${x.name}</p>`).join('')}
    `;
  }

  const diffSection = diff.hasChanges
    ? `<div style="background:#FFFBEB;border:1px solid #FDE68A;border-radius:8px;padding:16px;margin-bottom:20px;">
        <p style="margin:0 0 8px;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:2px;color:#B45309;">Configuration changes</p>
        ${diffRows('Categories', diff.categories)}
        ${diffRows('Statuses', diff.statuses)}
        ${diffRows('Notifications', diff.notifications)}
        ${diffRows('Workflows', diff.workflows)}
      </div>`
    : `<div style="background:#F0FDF4;border:1px solid #BBF7D0;border-radius:8px;padding:14px;margin-bottom:20px;">
        <p style="margin:0;font-size:13px;color:#16A34A;">No configuration changes detected vs original snapshot.</p>
      </div>`;

  const html = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/></head>
<body style="margin:0;padding:0;background:#FAF9F7;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
<div style="max-width:600px;margin:40px auto;padding:0 16px;">
  <div style="background:#1A1A1A;border-radius:12px 12px 0 0;padding:24px 32px;">
    <p style="margin:0;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:2px;color:#F97316;">Go-Live Report</p>
    <p style="margin:6px 0 0;font-size:22px;font-weight:800;color:#FFFFFF;">${orgName} — Go-Live</p>
  </div>
  <div style="background:#FFFFFF;border:1px solid #E5E2DC;border-top:none;border-radius:0 0 12px 12px;padding:32px;">
    <p style="margin:0 0 6px;font-size:13px;color:#6B7280;">Generated by ${saEmail} on ${date}</p>
    <div style="height:1px;background:#E5E2DC;margin:20px 0;"></div>
    ${diffSection}
    ${pdfUrl ? `<a href="${pdfUrl}" style="display:inline-block;background:#F97316;color:#FFFFFF;font-size:14px;font-weight:700;padding:14px 28px;border-radius:9999px;text-decoration:none;">Download full PDF report →</a>` : ''}
  </div>
  <p style="text-align:center;font-size:11px;color:#9CA3AF;margin-top:24px;">Zuper Onboarding Compass · <a href="mailto:onboarding@zuper.co" style="color:#F97316;">onboarding@zuper.co</a></p>
</div>
</body>
</html>`;

  return {
    subject: `[Go-Live] ${orgName} — Account Configuration Report`,
    html,
  };
}
