import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import type { SnapshotDiff, DiffItem } from '@/lib/zuper/diff';
import type { ZuperCategory, ZuperNotification, ZuperWorkflowSummary } from '@/lib/zuper/transformer';

const ORANGE = '#F97316';
const DARK   = '#1A1A1A';
const MUTED  = '#6B7280';
const BORDER = '#E5E2DC';
const GREEN  = '#16A34A';
const RED    = '#DC2626';

const s = StyleSheet.create({
  page:      { fontFamily: 'Helvetica', backgroundColor: '#FAF9F7', padding: 48 },
  eyebrow:   { fontSize: 9, fontWeight: 'bold', color: ORANGE, letterSpacing: 2, textTransform: 'uppercase', marginBottom: 8 },
  h1:        { fontSize: 26, fontWeight: 'bold', color: DARK, marginBottom: 6, lineHeight: 1.2 },
  h2:        { fontSize: 16, fontWeight: 'bold', color: DARK, marginBottom: 14 },
  h3:        { fontSize: 11, fontWeight: 'bold', color: DARK, marginBottom: 6 },
  body:      { fontSize: 10, color: MUTED, lineHeight: 1.5 },
  small:     { fontSize: 9,  color: MUTED },
  label:     { fontSize: 8,  fontWeight: 'bold', color: MUTED, textTransform: 'uppercase', letterSpacing: 1.5, marginBottom: 3 },
  card:      { backgroundColor: '#FFFFFF', borderRadius: 6, padding: 12, marginBottom: 6, borderWidth: 1, borderColor: BORDER },
  row:       { flexDirection: 'row', justifyContent: 'space-between' },
  divider:   { borderBottomWidth: 1, borderBottomColor: BORDER, marginVertical: 14 },
  addedRow:  { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
  dot:       { width: 6, height: 6, borderRadius: 3, marginRight: 8, marginTop: 2 },
  footer:    { position: 'absolute', bottom: 32, left: 48, right: 48, flexDirection: 'row', justifyContent: 'space-between' },
  section:   { marginBottom: 24 },
});

function DiffSection({ title, diff }: { title: string; diff: { added: DiffItem[]; removed: DiffItem[]; renamed: DiffItem[] } }) {
  if (!diff.added.length && !diff.removed.length && !diff.renamed.length) return null;
  return (
    <View style={s.section}>
      <Text style={s.h3}>{title}</Text>
      {diff.added.map((item, i) => (
        <View key={i} style={s.addedRow}>
          <View style={[s.dot, { backgroundColor: GREEN }]} />
          <Text style={[s.body, { color: GREEN }]}>Added: {item.name}</Text>
        </View>
      ))}
      {diff.removed.map((item, i) => (
        <View key={i} style={s.addedRow}>
          <View style={[s.dot, { backgroundColor: RED }]} />
          <Text style={[s.body, { color: RED }]}>Removed: {item.name}</Text>
        </View>
      ))}
      {diff.renamed.map((item, i) => (
        <View key={i} style={s.addedRow}>
          <View style={[s.dot, { backgroundColor: ORANGE }]} />
          <Text style={[s.body, { color: ORANGE }]}>Renamed: {item.oldName} → {item.name}</Text>
        </View>
      ))}
    </View>
  );
}

interface GoLiveReportProps {
  orgName: string;
  generatedBy: string;
  generatedAt: string;
  categories: ZuperCategory[];
  notifications: ZuperNotification[];
  workflows: ZuperWorkflowSummary[];
  diff: SnapshotDiff;
}

export function GoLiveReport({
  orgName, generatedBy, generatedAt, categories, notifications, workflows, diff,
}: GoLiveReportProps) {
  const date = new Date(generatedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return (
    <Document title={`${orgName} — Go-Live Report`}>
      {/* Cover */}
      <Page size="A4" style={s.page}>
        <View style={{ flex: 1, justifyContent: 'center' }}>
          <Text style={s.eyebrow}>Go-Live Configuration Report</Text>
          <Text style={s.h1}>{orgName}</Text>
          <Text style={[s.body, { marginBottom: 4 }]}>Generated by {generatedBy}</Text>
          <Text style={s.small}>{date}</Text>
          <View style={s.divider} />
          <View style={s.row}>
            <View><Text style={s.label}>Categories</Text><Text style={s.body}>{categories.length}</Text></View>
            <View><Text style={s.label}>Total statuses</Text><Text style={s.body}>{categories.reduce((n, c) => n + c.statuses.length, 0)}</Text></View>
            <View><Text style={s.label}>Notifications</Text><Text style={s.body}>{notifications.length}</Text></View>
            <View><Text style={s.label}>Workflows</Text><Text style={s.body}>{workflows.length}</Text></View>
          </View>
          {diff.hasChanges && (
            <View style={{ marginTop: 16, backgroundColor: '#FFF7ED', borderRadius: 8, padding: 12, borderWidth: 1, borderColor: '#FED7AA' }}>
              <Text style={[s.body, { color: ORANGE }]}>Configuration changes detected vs original snapshot. See Section 2.</Text>
            </View>
          )}
        </View>
        <View style={s.footer}>
          <Text style={s.small}>Zuper Onboarding Compass — Go-Live Report</Text>
          <Text style={s.small}>Confidential</Text>
        </View>
      </Page>

      {/* Current config */}
      <Page size="A4" style={s.page}>
        <Text style={s.eyebrow}>Section 1</Text>
        <Text style={s.h2}>Current account configuration</Text>

        <Text style={s.h3}>Job categories &amp; statuses</Text>
        {categories.map((cat) => (
          <View key={cat.uid} style={s.card}>
            <Text style={[s.body, { fontWeight: 'bold', color: DARK, marginBottom: 4 }]}>{cat.name}</Text>
            <Text style={s.body}>{cat.statuses.map((st) => st.name).join(' · ')}</Text>
          </View>
        ))}

        {notifications.length > 0 && (
          <View style={{ marginTop: 12 }}>
            <Text style={s.h3}>Notifications ({notifications.length})</Text>
            {notifications.slice(0, 8).map((n) => (
              <View key={n.uid} style={[s.card, { flexDirection: 'row', justifyContent: 'space-between' }]}>
                <Text style={s.body}>{n.name}</Text>
                <Text style={[s.small, { color: n.isActive ? GREEN : MUTED }]}>{n.isActive ? 'Active' : 'Inactive'}</Text>
              </View>
            ))}
            {notifications.length > 8 && <Text style={s.small}>+ {notifications.length - 8} more</Text>}
          </View>
        )}

        <View style={s.footer}>
          <Text style={s.small}>{orgName} — Go-Live Report</Text>
          <Text style={s.small}>Page 2</Text>
        </View>
      </Page>

      {/* Diff */}
      <Page size="A4" style={s.page}>
        <Text style={s.eyebrow}>Section 2</Text>
        <Text style={s.h2}>Changes vs original snapshot</Text>

        {!diff.hasChanges ? (
          <View style={{ backgroundColor: '#F0FDF4', borderRadius: 8, padding: 14, borderWidth: 1, borderColor: '#BBF7D0' }}>
            <Text style={[s.body, { color: GREEN }]}>No differences detected. Account matches the original snapshot.</Text>
          </View>
        ) : (
          <>
            <DiffSection title="Categories"    diff={diff.categories} />
            <DiffSection title="Statuses"      diff={diff.statuses} />
            <DiffSection title="Notifications" diff={diff.notifications} />
            <DiffSection title="Workflows"     diff={diff.workflows} />
          </>
        )}

        <View style={s.footer}>
          <Text style={s.small}>{orgName} — Go-Live Report</Text>
          <Text style={s.small}>Page 3</Text>
        </View>
      </Page>
    </Document>
  );
}
